### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by postatum** [aml-org/aml2html#22]
- [x] add tests
- [x] set up Travis

**Comment by postatum** [comment]
Added tests and merged to `master` along with some refactoring and bugfixes.

**Comment by postatum** [comment]
@jstoiko can you please enable Travis for this repo? I don't have the rights.

**Comment by jstoiko** [comment]
[done](https://travis-ci.org/aml-org/aml2html)

**Comment by postatum** [comment]
> [done](https://travis-ci.org/aml-org/aml2html)

Cool. Thank you
