### ISSUE TITLE
Create main index file for a set of dialects file

### ISSUE THREAD

**Issue by antoniogarrote** [aml-org/aml2html#9]
When invoking the generator for a set of dialect files, a top-level index.html file must be also created as an entry-point for the full group of dialects.

It must include:

- the dialects section with the full list of parsed dialects
- the schemas section with the full list of parsed schemas

The main content of the page should include a table with the list of dialects and the usage string.

Additionally, a title, version and a description for the set of files must be accepted as parameters and they must be displayed as headers for the main content in the index file.

**Comment by antoniogarrote** [comment]
Example of a similar index page in Javadoc with the list of packages: https://jena.apache.org/documentation/javadoc/jena/index.html

**Comment by postatum** [comment]
@antoniogarrote 
I don't understand this part:

> Additionally, a title, version and a description for the set of files must be accepted as parameters and they must be displayed as headers for the main content in the index file.

Please describe a use case - dialects, params values and the output.

**Comment by postatum** [comment]
@antoniogarrote other than the above comment, please pull `i9_dialects_index` branch and let me know if it looks they way you expected. Thanks!

**Comment by antoniogarrote** [comment]
Hi @postatum, it looks great.

I was thinking about the title, version and description as content for the index.html itself, not for the left side. The idea was to provide a little bit of (optional) context that could be displayed on top of the first table of dialects for the whole set of dialects that are being documented.

**Comment by antoniogarrote** [comment]
I have created https://github.com/aml-org/aml2html/pull/10 that should remove duplicates

**Comment by postatum** [comment]
> Hi @postatum, it looks great.
> 
> I was thinking about the title, version and description as content for the index.html itself, not for the left side. The idea was to provide a little bit of (optional) context that could be displayed on top of the first table of dialects for the whole set of dialects that are being documented.

Thanks. Understood.
